image: gitpod/workspace-full-vnc

ports:
  - port: 3306
    onOpen: ignore

tasks:
  - name: Setup MySQL
    init: |
      sudo service mysql start
      mysql -e "CREATE DATABASE IF NOT EXISTS studybuddy_db;"
      mysql -e "CREATE USER 'vicovt'@'%' IDENTIFIED BY 'vicky14';"
      mysql -e "GRANT ALL PRIVILEGES ON studybuddy_db.* TO 'vicovt'@'%';"
      mysql -e "FLUSH PRIVILEGES;"
  - name: Setup Symfony
    command: |
      cd StudyBuddy-api
      composer install
      php bin/console doctrine:database:create
      php bin/console doctrine:migrations:migrate

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - felixfbecker.php-intellisense
    - neilbrayfield.php-docblocker
    - formulahendry.auto-rename-tag
