image:
  file: gitpod.Dockerfile

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: open-preview

tasks:
  - name: Setup MySQL
    init: |
      /StudyBuddy/StudyBuddy-api/bin/setup_mysql.sh
  - name: Setup Symfony
    init: |
      cd StudyBuddy-api
      composer install
    command: php -S 0.0.0.0:8000 -t public
    env:
      SYMFONY_PROJECT_DIR: "/workspace/StudyBuddy/StudyBuddy-api"

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - felixfbecker.php-intellisense
    - neilbrayfield.php-docblocker
    - formulahendry.auto-rename-tag


