image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: open-preview

tasks:
  - name: Setup MySQL
    init: |
      sudo /usr/local/bin/setup_mysql.sh
  - name: Setup Symfony
    init: |
      cd StudyBuddy-api
      composer install
      php bin/console doctrine:database:create
    command: |
      php bin/console doctrine:migrations:migrate
      php -S 0.0.0.0:8000 -t public

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - felixfbecker.php-intellisense
    - neilbrayfield.php-docblocker
    - formulahendry.auto-rename-tag


